services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      # Database name 'ems' is logical for an Employee Management System
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: ems
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    container_name: springboot
    build:
      # FIX: Set context to the root directory for the correct Dockerfile path
      context: . 
      # FIX: Reference the Dockerfile from the project root
      dockerfile: Backend/backend.Dockerfile
    ports:
      # CRITICAL FIX: Maps host port 2025 to the correct Spring Boot port (8080)
      - "2025:8080" 
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      # Set context to the root of the React application
      context: ./Frontend/Employee-Client
      # FIX: The Dockerfile is located inside the context directory
      dockerfile: ./frontend.Dockerfile 
    ports:
      # Host port 3000 mapped to Nginx default port (80)
      - "3000:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data:
